### PR TITLE
add list of things we maintain

### PR DESCRIPTION
**Pull request by afeld**

### CODE REVIEW

**Comment by DavidEBest** [comment]
Is Before You Ship going to officially be maintained by the compliance toolkit team? If so, then looks good to me.

**Comment by mbland** [comment]
Good question, @DavidEBest. I thought "Before You Ship" was the name of the product lead guide by @hollyallen and @annahsebok.

**Comment by annahsgraves** [comment]
"Before You Ship" is a SECTION of the PM guide being worked on by Leah in
enormous collaboration with Aidan and Bret. The "Before You Ship" guide
exists OUTSIDE of the PM guide and will be linked to it there.

On Tuesday, December 29, 2015, Mike Bland notifications@github.com wrote:

> Good question, @DavidEBest https://github.com/DavidEBest. I thought
> "Before You Ship" was the name of the product lead guide by @hollyallen
> https://github.com/hollyallen and @annahsebok
> https://github.com/annahsebok.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/18F/compliance-toolkit/pull/3#issuecomment-167827686.

## 

Anna Heller Sebok
18F Innovation Operations Specialist
General Services Administration
1800 F Street NW
Washington, DC 20006
202.403.7245
anna.sebok@gsa.gov

**Comment by afeld** [comment]
> Is Before You Ship going to officially be maintained by the compliance toolkit team?

Good catch. Clarified it a bit.

> "Before You Ship" is a SECTION of the PM guide

Minor nit: I wouldn't quite put it that way, since Before You Ship is applicable to more than the Product perspective. @leahbannon and I had a good discussion about what the relationship between the two should be a couple weeks ago, so I think we're on the same page about it. We're keeping close eyes on each to make sure that they link back and forth where appropriate, and that there isn't duplication.

/cc @mogul

**Comment by DavidEBest** [comment]
:+1: Works for me.

**Comment by annahsgraves** [comment]
Yes, Aidan, what I'm trying to say is that there are essentially two - the
Before You Ship guide you're working on and the PM view of B.Y.S.

I want to make it clear that this is not THE PM GUIDE as was originally
asked in this thread, nor is it being driven by team Product (as it
shouldn't be). We are only referencing back to the primary guide built by
Aidan and adding any additional info in the context of our guide that could
be helpful specific to the PMs role in that process.

On Tuesday, December 29, 2015, David Best notifications@github.com wrote:

> [image: :+1:] Works for me.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/18F/compliance-toolkit/pull/3#issuecomment-167830301.

## 

Anna Heller Sebok
18F Innovation Operations Specialist
General Services Administration
1800 F Street NW
Washington, DC 20006
202.403.7245
anna.sebok@gsa.gov

**Pull request merged**
